version: 2
updates:
  - package-ecosystem: "gomod"
    # Update go.mod files stored in these directories daily 
    directories:
      - "/"
      - "/hack/tools"
    schedule:
      interval: "daily"
